config/routes.rb
Rails.application.routes.draw do
  resources :practices
  resources :posts
  resources :people
  devise_for :customers, :path_names=>{:sign_in => :signing}
  root to: 'students#index'
  resources :users
  resource :test
  resolve('Test') { [:test] }
  resources :students do
    resources :comments
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/student.rb
class Student < ApplicationRecord
  has_many :comments, dependent: :destroy
  validates :roll_no, length: {is: 10}
  validate :check_name
  around_save :some_action

  attr_accessor :batch

  def check_name
    if name == "Mohammad Fahad"
        errors.add(:name, "should not be Mohammad Fahad")
    end
  end
  def some_action
    new_rec = new_record?
    yield
    return if !new_rec
    puts"this is a new record"
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  # before_action :authenticate_customer!, :except=>[:index,:show]
  def index
    @students = Student.all
    flash.keep
  end

  def show
    @student = Student.find(params[:id])
    flash.keep
  end

  def new
    @student = Student.new
  end

  def edit
    @student = Student.find(params[:id])
  end

  def create
    
    @student = Student.new(params.require(:student).permit(:name, :roll_no, :semster))
    if @student.valid? && @student.save
      # UserMailer.with(user: @student).welcome_email.deliver_later
      redirect_to students_path, flash: { referral_code: 1234 }

    else
      render :new
    end
  end

  def update
    @student = Student.find(params[:id])
    if @student.update(params.require(:student).permit(:name, :roll_no, :semster))
      redirect_to students_path
    else
      render :edit
    end
  end
  
  def destroy
    @student = Student.find(params[:id])
    @student.destroy
    redirect_to students_path
  end

  private

  def authentication_check
   authenticate_or_request_with_http_basic do |user, password|
    user == 'USER' && password == 'PASSWORD'
   end
  end
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/students/_form.html.erb
<% if @student.errors.any? %>
  <h2><%= pluralize(@student.errors.count, "error") %> prohibited this article from being saved:</h2>
    <ul>
      <% @student.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
<% end %>
<%= form_with model: @student, local: true do |form| %>
    <p>
        <%= form.label :Name %><br>
        <%= form.text_field :name %>
    </p>
 
  <p>
    <%= form.label :Roll_no %><br>
    <%= form.text_field :roll_no %>
  </p>
   <p>
    <%= form.label :Semester %><br>
    <%= form.text_field :semster %>
  </p>
 
  <p>
    <%= form.submit :Submit %>
  </p>


 <% end %>

app/views/students/create.html.erb
<h3>Congratulation Successfully Submitted</h3>
<br>
<%= link_to 'Main Page', students_path%>

app/views/students/destroy.html.erb
<h3>Congratulation Deleted Successfully</h3>
<br>
<%= link_to 'Main Page', students_path%>

app/views/students/edit.html.erb
<center><h1> Update Student</h1></center>
<%= render 'form' %>
<%= link_to 'Back', students_path %>

app/views/students/index.html.erb
<%=link_to 'Add New Student', new_student_path%>
<br>
<br>
<br>
<h1>Listing Students</h1>
 
<table>
  <tr>
    <th style="border: 1px solid black">Student Name</th>
    <th style="border: 1px solid black">Roll No</th>
    <th style="border: 1px solid black">Semester</th>
    <th style="border: 1px solid black">Show Student</th>
    <th style="border: 1px solid black">Edit Student</th>
    <th style="border: 1px solid black">Delete Student</th>


  </tr>
 
  <% @students.each do |student| %>
    <tr>
      <td style="border: 1px solid black"><%= student.name %></td>
      <td style="border: 1px solid black"><%= student.roll_no %></td>
      <td style="border: 1px solid black"><%= student.semster %></td>
      <td style="border: 1px solid black"><%= link_to 'Show', student_path(student) %></td>
      <td style="border: 1px solid black"><%= link_to 'Edit', edit_student_path(student) %></td>
      <td style="border: 1px solid black"><%= link_to 'Delete', student_path(student), method: :delete, data: { confirm: 'Are you sure?' } %></td>


    </tr>
  <% end %>
</table>

app/views/students/new.html.erb
<center><h1> Enter New Student</h1></center>
<%= render 'form' %>
<%= link_to 'Back', students_path %>

app/views/students/show.html.erb
<p>
  <strong>Student Name:</strong>
  <%= @student.name %>
</p>
 
<p>
  <strong>Student Roll No:</strong>
  <%= @student.roll_no  %>
</p>
<p>
  <strong>Student Semester:</strong>
  <%= @student.semster  %>
</p>
<br>
<h2>Teacher's Comments About you</h2>
<%= render @student.comments %>

<h2>Add a comment:</h2>
<%= render 'comments/form' %>

<%= link_to 'Back', students_path %>

app/views/students/update.html.erb
<h3>Congratulation Updated Successfully</h3>
<br>
<%= link_to 'Main Page', students_path%>