config/routes.rb
Rails.application.routes.draw do
  resources :practices
  resources :posts
  resources :people
  devise_for :customers, :path_names=>{:sign_in => :signing}
  root to: 'students#index'
  resources :users
  resource :test
  resolve('Test') { [:test] }
  resources :students do
    resources :comments
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/practice.rb
class Practice < ApplicationRecord
end

app/controllers/practices_controller.rb
class PracticesController < ApplicationController
  before_action :set_practice, only: %i[ show edit update destroy ]

  # GET /practices or /practices.json
  def index
    @practices = Practice.all
  end

  # GET /practices/1 or /practices/1.json
  def show
  end

  # GET /practices/new
  def new
    @practice = Practice.new
  end

  # GET /practices/1/edit
  def edit
  end

  # POST /practices or /practices.json
  def create
    @practice = Practice.new(practice_params)

    respond_to do |format|
      if @practice.save
        format.html { redirect_to practice_url(@practice), notice: "Practice was successfully created." }
        format.json { render :show, status: :created, location: @practice }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @practice.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /practices/1 or /practices/1.json
  def update
    respond_to do |format|
      if @practice.update(practice_params)
        format.html { redirect_to practice_url(@practice), notice: "Practice was successfully updated." }
        format.json { render :show, status: :ok, location: @practice }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @practice.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /practices/1 or /practices/1.json
  def destroy
    @practice.destroy

    respond_to do |format|
      format.html { redirect_to practices_url, notice: "Practice was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_practice
      @practice = Practice.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def practice_params
      params.fetch(:practice, {})
    end
end

app/helpers/practices_helper.rb
module PracticesHelper
end

app/views/practices/_form.html.erb
<%= form_with(model: practice, local: true) do |form| %>
  <% if practice.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(practice.errors.count, "error") %> prohibited this practice from being saved:</h2>

      <ul>
      <% practice.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/practices/edit.html.erb
<h1>Editing Practice</h1>

<%= render 'form', practice: @practice %>

<%= link_to 'Show', @practice %> |
<%= link_to 'Back', practices_path %>

app/views/practices/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Practices</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @practices.each do |practice| %>
      <tr>
        <td><%= link_to 'Show', practice %></td>
        <td><%= link_to 'Edit', edit_practice_path(practice) %></td>
        <td><%= link_to 'Destroy', practice, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Practice', new_practice_path %>

app/views/practices/new.html.erb
<h1>New Practice</h1>

<%= render 'form', practice: @practice %>

<%= link_to 'Back', practices_path %>

app/views/practices/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_practice_path(@practice) %> |
<%= link_to 'Back', practices_path %>